export interface TaskField {
  key: string;
  label: string;
  type: 'input' | 'textarea' | 'select' | 'date';
  options?: string[];
}

export interface TaskConfig {
  name: string;
  fields: TaskField[];
  apiUrl?: string;
  token?: string;
  stage?: number;
}

export const taskConfigs: Record<string, TaskConfig> = {
  workTeam: {
    name: '工作团队确认',
    stage: 1,
    fields: [
      { key: 'TDFZR', label: '团队负责人', type: 'input' },
      { key: 'ZHZCY', label: '综合组成员', type: 'input' },
      { key: 'CXZCY', label: '程序组成员', type: 'input' },
      { key: 'CCGLZCY', label: '财产管理组成员', type: 'input' },
      { key: 'ZQSHZCY', label: '债权审核组成员', type: 'input' },
      { key: 'LDRSZCY', label: '劳动人事组成员', type: 'input' },
      { key: 'ZZQLZCY', label: '债权确认组成员', type: 'input' },
    ],
    apiUrl: '/api/web/getWorkTeam',
    token: '4015f285dc41bd1bb931ba8430966c3f',
  },
  workPlan: {
    name: '工作计划确认',
    stage: 1,
    fields: [
      { key: 'JHLX', label: '计划类型', type: 'input' },
      { key: 'JHNR', label: '计划内容', type: 'textarea' },
      { key: 'KSRQ', label: '开始日期', type: 'date' },
      { key: 'JSRQ', label: '结束日期', type: 'date' },
      { key: 'FZR', label: '负责人', type: 'input' },
      { key: 'ZHZT', label: '综合状态', type: 'input' },
    ],
    apiUrl: '/api/web/getWorkPlan',
    token: '8a62e323a84173fd8ec72557e6fc616d',
  },
  management: {
    name: '管理制度确认',
    stage: 1,
    fields: [
      { key: 'GLMC', label: '管理制度名称', type: 'input' },
      { key: 'GLNR', label: '管理制度内容', type: 'textarea' },
      { key: 'FZR', label: '负责人', type: 'input' },
      { key: 'FBRQ', label: '发布日期', type: 'date' },
      { key: 'SYFW', label: '适用范围', type: 'input' },
    ],
    apiUrl: '/api/web/getManagement',
    token: '6bbdf0bf97117c1bac495072c961e778',
  },
  sealManagement: {
    name: '印章确认',
    stage: 1,
    fields: [
      { key: 'YZMC', label: '印章名称', type: 'input' },
      {
        key: 'YZZT',
        label: '印章状态',
        type: 'select',
        options: ['正常', '停用', '销毁'],
      },
      { key: 'GLR', label: '管理人', type: 'input' },
      { key: 'GLRQ', label: '管理日期', type: 'date' },
      { key: 'BZ', label: '备注', type: 'textarea' },
    ],
    apiUrl: '/api/web/getSealManagement',
    token: '203cadf061d22b2aaa2ce1c59b9c4bbb',
  },
  legalProcedure: {
    name: '法律程序确认',
    stage: 1,
    fields: [
      { key: 'CXMC', label: '程序名称', type: 'input' },
      { key: 'CXNR', label: '程序内容', type: 'textarea' },
      { key: 'KSRQ', label: '开始日期', type: 'date' },
      { key: 'JSRQ', label: '结束日期', type: 'date' },
      { key: 'FZR', label: '负责人', type: 'input' },
      {
        key: 'CXZT',
        label: '程序状态',
        type: 'select',
        options: ['进行中', '已完成', '已终止'],
      },
    ],
    apiUrl: '/api/web/getLegalProcedure',
    token: 'a81a3a18b6d52abb4b6c38132e1198da',
  },
  propertyReceipt: {
    name: '财产接管确认',
    stage: 2,
    fields: [
      { key: 'CCJGRQ', label: '接管日期', type: 'date' },
      { key: 'CCJGNR', label: '接管内容', type: 'textarea' },
      { key: 'FZR', label: '负责人', type: 'input' },
      { key: 'JGZT', label: '接管状态', type: 'input' },
      { key: 'BZ', label: '备注', type: 'textarea' },
    ],
    apiUrl: '/api/web/getPropertyReceipt',
    token: '699a11d9338b983ce9eafc5e75f1833f',
  },
  emergency: {
    name: '应急预案确认',
    stage: 2,
    fields: [
      { key: 'YJYAMC', label: '应急预案名称', type: 'input' },
      { key: 'YJYANR', label: '应急预案内容', type: 'textarea' },
      { key: 'FZR', label: '负责人', type: 'input' },
      { key: 'YJZT', label: '应急状态', type: 'input' },
      { key: 'BZ', label: '备注', type: 'textarea' },
    ],
    apiUrl: '/api/web/getEmergency',
    token: 'c6c85c5e695fec908ded4f05f9e9bfc9',
  },
  propertyPlan: {
    name: '财产处置计划确认',
    stage: 2,
    fields: [
      { key: 'CCJHMC', label: '财产计划名称', type: 'input' },
      { key: 'CCJHNR', label: '财产计划内容', type: 'textarea' },
      { key: 'KSRQ', label: '开始日期', type: 'date' },
      { key: 'JSRQ', label: '结束日期', type: 'date' },
      { key: 'FZR', label: '负责人', type: 'input' },
      { key: 'JHZT', label: '计划状态', type: 'input' },
    ],
    apiUrl: '/api/web/getPropertyPlan',
    token: '924180f974b81f375d6625ab0fd59f60',
  },
  personnelEmp: {
    name: '人事管理确认',
    stage: 2,
    fields: [
      { key: 'RSGLNR', label: '人事管理内容', type: 'textarea' },
      { key: 'FZR', label: '负责人', type: 'input' },
      { key: 'GLRQ', label: '管理日期', type: 'date' },
      { key: 'GLZT', label: '管理状态', type: 'input' },
      { key: 'BZ', label: '备注', type: 'textarea' },
    ],
    apiUrl: '/api/web/getPersonnelEmp',
    token: 'ae3987ea39249e94edb9bdccf1c859d7',
  },
  internalAffairs: {
    name: '内部事务确认',
    stage: 2,
    fields: [
      { key: 'NBSWNR', label: '内部事务内容', type: 'textarea' },
      { key: 'FZR', label: '负责人', type: 'input' },
      { key: 'CLRQ', label: '处理日期', type: 'date' },
      { key: 'SWZT', label: '事务状态', type: 'input' },
      { key: 'BZ', label: '备注', type: 'textarea' },
    ],
    apiUrl: '/api/web/getInternalAffairs',
    token: 'ba251b8fffee8a47a71b3429ab9cccb5',
  },
  businessManagement: {
    name: '经营管理确认',
    stage: 2,
    fields: [
      { key: 'JYGLNR', label: '经营管理内容', type: 'textarea' },
      { key: 'FZR', label: '负责人', type: 'input' },
      { key: 'GLRQ', label: '管理日期', type: 'date' },
      { key: 'GLZT', label: '管理状态', type: 'input' },
      { key: 'BZ', label: '备注', type: 'textarea' },
    ],
    apiUrl: '/api/web/getBusinessManagement',
    token: '0611b92b9a4bd76e5fc315d145a90fc2',
  },
  propertyInvestigation: {
    name: '财产调查',
    stage: 3,
    fields: [
      { key: 'TCLX', label: '调查类型', type: 'input' },
      { key: 'TCNR', label: '调查内容', type: 'textarea' },
      { key: 'TCRQ', label: '调查日期', type: 'date' },
      { key: 'TCR', label: '调查人', type: 'input' },
      { key: 'TCFX', label: '调查方向', type: 'input' },
      { key: 'TCZT', label: '调查状态', type: 'input' },
    ],
    apiUrl: '/api/web/getAllPropertyInvestigation',
    token: '17fce65ebabe3088ab45b97f77f91b5a',
  },
  bankExpenses: {
    name: '银行费用',
    stage: 3,
    fields: [
      { key: 'TCLX', label: '调查类型', type: 'input' },
      { key: 'TCNR', label: '调查内容', type: 'textarea' },
      { key: 'TCRQ', label: '调查日期', type: 'date' },
      { key: 'TCR', label: '调查人', type: 'input' },
      { key: 'TCFX', label: '调查方向', type: 'input' },
      { key: 'TCZT', label: '调查状态', type: 'input' },
    ],
    apiUrl: '/api/web/getAllBankExpenses',
    token: 'ff7185ba1adffaa6630ec57062ae6473',
  },
  rightsClaim: {
    name: '权利主张',
    stage: 3,
    fields: [
      { key: 'TCLX', label: '调查类型', type: 'input' },
      { key: 'TCNR', label: '调查内容', type: 'textarea' },
      { key: 'TCRQ', label: '调查日期', type: 'date' },
      { key: 'TCR', label: '调查人', type: 'input' },
      { key: 'TCFX', label: '调查方向', type: 'input' },
      { key: 'TCZT', label: '调查状态', type: 'input' },
    ],
    apiUrl: '/api/web/getAllRightsClaim',
    token: '0ce8909084c3cd60a2e2f8ba450df13a',
  },
  reclaimReview: {
    name: '回收审核',
    stage: 3,
    fields: [
      { key: 'TCLX', label: '调查类型', type: 'input' },
      { key: 'TCNR', label: '调查内容', type: 'textarea' },
      { key: 'TCRQ', label: '调查日期', type: 'date' },
      { key: 'TCR', label: '调查人', type: 'input' },
      { key: 'TCFX', label: '调查方向', type: 'input' },
      { key: 'TCZT', label: '调查状态', type: 'input' },
    ],
    apiUrl: '/api/web/getAllReclaimReview',
    token: 'dcdc3c95faccd88d495c94923f8e2148',
  },
  litigationArbitration: {
    name: '诉讼仲裁',
    stage: 3,
    fields: [
      { key: 'TCLX', label: '调查类型', type: 'input' },
      { key: 'TCNR', label: '调查内容', type: 'textarea' },
      { key: 'TCRQ', label: '调查日期', type: 'date' },
      { key: 'TCR', label: '调查人', type: 'input' },
      { key: 'TCFX', label: '调查方向', type: 'input' },
      { key: 'TCZT', label: '调查状态', type: 'input' },
    ],
    apiUrl: '/api/web/getAllLitigationArbitration',
    token: '7adbf35a9986045cb55ce9e1d8d8b90c',
  },
  creditorClaim: {
    name: '债权人申报',
    stage: 3,
    fields: [
      { key: 'TCLX', label: '调查类型', type: 'input' },
      { key: 'TCNR', label: '调查内容', type: 'textarea' },
      { key: 'TCRQ', label: '调查日期', type: 'date' },
      { key: 'TCR', label: '调查人', type: 'input' },
      { key: 'TCFX', label: '调查方向', type: 'input' },
      { key: 'TCZT', label: '调查状态', type: 'input' },
    ],
    apiUrl: '/api/web/getAllCreditorClaim',
    token: '7fb219c01b0107dc5cb58d173ce87664',
  },
  socialSF: {
    name: '社保费用表',
    stage: 3,
    fields: [
      { key: 'TCLX', label: '调查类型', type: 'input' },
      { key: 'TCNR', label: '调查内容', type: 'textarea' },
      { key: 'TCRQ', label: '调查日期', type: 'date' },
      { key: 'TCR', label: '调查人', type: 'input' },
      { key: 'TCFX', label: '调查方向', type: 'input' },
      { key: 'TCZT', label: '调查状态', type: 'input' },
    ],
    apiUrl: '/api/web/getAllSociaSF',
    token: 'a8990ffa15ebbd2bff6aed37db08cadf',
  },
  taxVerification: {
    name: '税收核定表',
    stage: 3,
    fields: [
      { key: 'TCLX', label: '调查类型', type: 'input' },
      { key: 'TCNR', label: '调查内容', type: 'textarea' },
      { key: 'TCRQ', label: '调查日期', type: 'date' },
      { key: 'TCR', label: '调查人', type: 'input' },
      { key: 'TCFX', label: '调查方向', type: 'input' },
      { key: 'TCZT', label: '调查状态', type: 'input' },
    ],
    apiUrl: '/api/web/getAllTaxVerification',
    token: '59a21e973cc5a522c63b11c19a988d0b',
  },
  session: {
    name: '第一次债权人会议',
    stage: 4,
    fields: [
      { key: 'HYLX', label: '会议类型', type: 'input' },
      { key: 'HYZT', label: '会议主题', type: 'input' },
      { key: 'HYRQ', label: '会议日期', type: 'date' },
      { key: 'HYDD', label: '会议地点', type: 'input' },
      { key: 'ZCR', label: '主持人', type: 'input' },
      { key: 'CHRS', label: '参会人数', type: 'input' },
    ],
  },
  meetingDocuments: {
    name: '会议文件',
    stage: 4,
    fields: [
      { key: 'WJMC', label: '文件名称', type: 'input' },
      { key: 'WJLX', label: '文件类型', type: 'input' },
      { key: 'WJNR', label: '文件内容', type: 'textarea' },
      { key: 'SCRQ', label: '上传日期', type: 'date' },
      { key: 'SCR', label: '上传人', type: 'input' },
    ],
  },
  claimConfirmation: {
    name: '债权确认',
    stage: 4,
    fields: [
      { key: 'ZQRM', label: '债权人名称', type: 'input' },
      { key: 'ZQJE', label: '债权金额', type: 'input' },
      { key: 'ZQLX', label: '债权类型', type: 'input' },
      { key: 'QRQ', label: '确认日期', type: 'date' },
      { key: 'QRZT', label: '确认状态', type: 'input' },
    ],
  },
  importantActions: {
    name: '重要行为',
    stage: 4,
    fields: [
      { key: 'XWMC', label: '行为名称', type: 'input' },
      { key: 'XWLX', label: '行为类型', type: 'input' },
      { key: 'XWNR', label: '行为内容', type: 'textarea' },
      { key: 'FSRQ', label: '发生日期', type: 'date' },
      { key: 'FZR', label: '负责人', type: 'input' },
    ],
  },
  setoffReview: {
    name: '抵销审核',
    stage: 4,
    fields: [
      { key: 'DXJE', label: '抵销金额', type: 'input' },
      { key: 'DXLX', label: '抵销类型', type: 'input' },
      { key: 'SHRQ', label: '审核日期', type: 'date' },
      { key: 'SHZT', label: '审核状态', type: 'input' },
      { key: 'SHR', label: '审核人', type: 'input' },
    ],
  },
  auditReport: {
    name: '审计报告',
    stage: 4,
    fields: [
      { key: 'BGMC', label: '报告名称', type: 'input' },
      { key: 'BGBH', label: '报告编号', type: 'input' },
      { key: 'BGNR', label: '报告内容', type: 'textarea' },
      { key: 'CJRQ', label: '出具日期', type: 'date' },
      { key: 'CJJG', label: '出具机构', type: 'input' },
    ],
  },
  assetValuation: {
    name: '资产价值评估',
    stage: 5,
    fields: [
      { key: 'PGXM', label: '评估项目', type: 'input' },
      { key: 'PGJZ', label: '评估价值', type: 'input' },
      { key: 'PGRQ', label: '评估日期', type: 'date' },
      { key: 'PGJG', label: '评估机构', type: 'input' },
      { key: 'PGBGBH', label: '评估报告编号', type: 'input' },
    ],
  },
  propertyVPlan: {
    name: '财产变价方案',
    stage: 5,
    fields: [
      { key: 'FAMC', label: '方案名称', type: 'input' },
      { key: 'BJFS', label: '变价方式', type: 'input' },
      { key: 'FANC', label: '方案内容', type: 'textarea' },
      { key: 'ZDRQ', label: '制定日期', type: 'date' },
      { key: 'FZR', label: '负责人', type: 'input' },
    ],
  },
  bankruptcyDeclaration: {
    name: '破产宣告',
    stage: 5,
    fields: [
      { key: 'XGRQ', label: '宣告日期', type: 'date' },
      { key: 'XGH', label: '宣告文号', type: 'input' },
      { key: 'XGYY', label: '宣告法院', type: 'input' },
      { key: 'XGNR', label: '宣告内容', type: 'textarea' },
    ],
  },
  propertyVIM: {
    name: '财产分配方案',
    stage: 5,
    fields: [
      { key: 'FAMC', label: '方案名称', type: 'input' },
      { key: 'FPZE', label: '分配总额', type: 'input' },
      { key: 'FPFS', label: '分配方式', type: 'input' },
      { key: 'FANC', label: '方案内容', type: 'textarea' },
      { key: 'ZDRQ', label: '制定日期', type: 'date' },
    ],
  },
  bankruptcyDistPlan: {
    name: '破产财产分配方案',
    stage: 6,
    fields: [
      { key: 'FAMC', label: '方案名称', type: 'input' },
      { key: 'FPZE', label: '分配总额', type: 'input' },
      { key: 'FPFS', label: '分配方式', type: 'input' },
      { key: 'FANC', label: '方案内容', type: 'textarea' },
      { key: 'ZDRQ', label: '制定日期', type: 'date' },
    ],
  },
  employeeSPlan: {
    name: '员工安置方案',
    stage: 6,
    fields: [
      { key: 'FAMC', label: '方案名称', type: 'input' },
      { key: 'FPZE', label: '分配总额', type: 'input' },
      { key: 'FPFS', label: '分配方式', type: 'input' },
      { key: 'FANC', label: '方案内容', type: 'textarea' },
      { key: 'ZDRQ', label: '制定日期', type: 'date' },
    ],
  },
  priorityPayment: {
    name: '优先受偿权',
    stage: 6,
    fields: [
      { key: 'FAMC', label: '方案名称', type: 'input' },
      { key: 'FPZE', label: '分配总额', type: 'input' },
      { key: 'FPFS', label: '分配方式', type: 'input' },
      { key: 'FANC', label: '方案内容', type: 'textarea' },
      { key: 'ZDRQ', label: '制定日期', type: 'date' },
    ],
  },
  propertyDEC: {
    name: '财产状况说明',
    stage: 6,
    fields: [
      { key: 'FAMC', label: '方案名称', type: 'input' },
      { key: 'FPZE', label: '分配总额', type: 'input' },
      { key: 'FPFS', label: '分配方式', type: 'input' },
      { key: 'FANC', label: '方案内容', type: 'textarea' },
      { key: 'ZDRQ', label: '制定日期', type: 'date' },
    ],
  },
  depositManagement: {
    name: '存款管理',
    stage: 6,
    fields: [
      { key: 'FAMC', label: '方案名称', type: 'input' },
      { key: 'FPZE', label: '分配总额', type: 'input' },
      { key: 'FPFS', label: '分配方式', type: 'input' },
      { key: 'FANC', label: '方案内容', type: 'textarea' },
      { key: 'ZDRQ', label: '制定日期', type: 'date' },
    ],
  },
  canRR: {
    name: '债权人会议决议',
    stage: 7,
    fields: [
      { key: 'FAMC', label: '方案名称', type: 'input' },
      { key: 'FPZE', label: '分配总额', type: 'input' },
      { key: 'FPFS', label: '分配方式', type: 'input' },
      { key: 'FANC', label: '方案内容', type: 'textarea' },
      { key: 'ZDRQ', label: '制定日期', type: 'date' },
    ],
  },
  terminationLiti: {
    name: '终止诉讼',
    stage: 7,
    fields: [
      { key: 'FAMC', label: '方案名称', type: 'input' },
      { key: 'FPZE', label: '分配总额', type: 'input' },
      { key: 'FPFS', label: '分配方式', type: 'input' },
      { key: 'FANC', label: '方案内容', type: 'textarea' },
      { key: 'ZDRQ', label: '制定日期', type: 'date' },
    ],
  },
  additionalDisiribution: {
    name: '追加分配',
    stage: 7,
    fields: [
      { key: 'FAMC', label: '方案名称', type: 'input' },
      { key: 'FPZE', label: '分配总额', type: 'input' },
      { key: 'FPFS', label: '分配方式', type: 'input' },
      { key: 'FANC', label: '方案内容', type: 'textarea' },
      { key: 'ZDRQ', label: '制定日期', type: 'date' },
    ],
  },
};

export const stageMapping: Record<string, number> = {
  workTeam: 1,
  workPlan: 1,
  management: 1,
  sealManagement: 1,
  legalProcedure: 1,
  propertyReceipt: 2,
  emergency: 2,
  propertyPlan: 2,
  personnelEmp: 2,
  internalAffairs: 2,
  businessManagement: 2,
  propertyInvestigation: 3,
  bankExpenses: 3,
  rightsClaim: 3,
  reclaimReview: 3,
  litigationArbitration: 3,
  creditorClaim: 3,
  socialSF: 3,
  taxVerification: 3,
  session: 4,
  meetingDocuments: 4,
  claimConfirmation: 4,
  importantActions: 4,
  setoffReview: 4,
  auditReport: 4,
  assetValuation: 5,
  propertyVPlan: 5,
  bankruptcyDeclaration: 5,
  propertyVIM: 5,
  bankruptcyDistPlan: 6,
  employeeSPlan: 6,
  priorityPayment: 6,
  propertyDEC: 6,
  depositManagement: 6,
  canRR: 7,
  terminationLiti: 7,
  additionalDisiribution: 7,
};

export const taskTypeToOperateType: Record<string, string> = {
  workTeam: '0',
  workPlan: '1',
  management: '2',
  sealManagement: '3',
  legalProcedure: '4',
  propertyReceipt: '0',
  emergency: '1',
  propertyPlan: '2',
  personnelEmp: '3',
  internalAffairs: '4',
  businessManagement: '5',
  propertyInvestigation: '0',
  bankExpenses: '1',
  rightsClaim: '2',
  reclaimReview: '3',
  litigationArbitration: '4',
  creditorClaim: '5',
  socialSF: '6',
  taxVerification: '7',
};

export const updateApiUrls: Record<number, string> = {
  1: 'http://192.168.0.107:8085/api/web/update1?token=ff3378dd6264d6a0d4293d322e738a85',
  2: 'http://192.168.0.107:8085/api/web/update2?token=5781352a1e8bd95e5fa74f0ff47074c5',
  3: 'http://192.168.0.107:8085/api/web/update3?token=da90b1901ed746289dd074c1af9dfa55',
};
